### ISSUE TITLE
question

### ISSUE THREAD

**Issue by theoneandonly-vector** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#1]
hey there,

can you show me a compatible dual-band (2,4 + 5ghz at the same time) usb wifi?

**Comment by johanlike** [comment]
@theoneandonly-vector  Rt5572 network card
Rt8814au/8812au is also available. I will compile these two drivers in my spare time.

**Comment by johanlike** [comment]
@theoneandonly-vector  The kernel now supports rt5572

**Comment by theoneandonly-vector** [comment]
thx perfect :)
