### ISSUE TITLE
Rtl8188eu not work but can identify 

### ISSUE THREAD

**Issue by wangmu0579** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#10]
We can see usb wifi identify but wifite only have wlan0.
could some one help?

root@kali:/lib# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:/lib#
root@kali:/lib
Interface   PHY   Driver              Chipset       
-----------------------------------------------------------------------
 1. p2p0        phy0  icnss               Not pci, usb, or sdio
 2. wlan0       phy0  icnss               Not pci, usb, or sdio

**Comment by wangmu0579** [comment]
My problem should be:My external wifi network usb dongle RTL8188eu can't work on onePlus6T.
Could some one help?
![710814387](https://user-images.githubusercontent.com/24429869/57983103-b144f600-7a80-11e9-897f-018cf2eedea6.jpg)
![433589119](https://user-images.githubusercontent.com/24429869/57983104-b2762300-7a80-11e9-96f4-951d73e8c974.jpg)
![969530677](https://user-images.githubusercontent.com/24429869/57983105-b3a75000-7a80-11e9-9926-fe8de17ef507.jpg)

**Comment by johanlike** [comment]
Added rtl8188eu ko module. Load the relevant module using insmod r8188eu.ko under the Android shell. Try to see if you can use the relevant driver.

**Comment by kimocoder** [comment]
@johanlike 

https://github.com/aircrack-ng/rtl8188eus -b v5.3.9

That branch has monitor mode and frame injection :+1:
