### ISSUE TITLE
没有交流群了吗？

### ISSUE THREAD

**Issue by ParticleG** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#13]
现在不管是看b站还是另外地方给的群地址都失效了

**Comment by johanlike** [comment]
https://github.com/johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#%E8%81%94%E7%B3%BB%E6%96%B9%E5%BC%8F
