### ISSUE TITLE
Where can i download releases?

### ISSUE THREAD

**Issue by Owningle** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#15]
I have noticed that this repo doesn't contain any source code, however, there is source code in a different repo you have made. I'm new to this and am not sure how to build it if you could point me in the direction of instructions on how to build, or where the releases are, I'd be grateful, thanks :)

**Comment by lisksemen** [comment]
Hi! I have downloaded the version beta 69 before it'd been deleted and if you want, I can share it with you
Sorry for my English)

**Comment by lisksemen** [comment]
https://drive.google.com/file/d/1-OrLEIIIWDaSOql3WI0FMbGIanCSlMQV/view?usp=drivesdk 
This is the link where from you can download it

**Comment by roukeerobin** [comment]
hi dear lisksemen. can you share with me the beta 69. I had download the beta68, I would appreciate it if you would like to share it with google driver.
