### ISSUE TITLE
求助第三方ROM

### ISSUE THREAD

**Issue by d0gkiller87** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#4]
*(inappropriate post removed)*

**Comment by johanlike** [comment]
@vungsung 这个得看有没有时间，我工作时间很忙，这些基本都是业余时间搞的。如果我时间足够我会出其他的版本。

**Comment by johanlike** [comment]
如果你现在的手机不是1+6或者1+6T的话建议你还是等等吧，1+7快出了，我不是很喜欢1+6T的屏幕。。。到时候我会做1+7的适配。

**Comment by vungsung** [comment]
是啊, 小弟的手機是1+6T, 只是用第三方ROM- 所以說kernel可以通用囉 :)

**Comment by johanlike** [comment]
你可以尝试一下，应该是通用的。如果有问题在告诉我。

**Comment by vungsung** [comment]
好, 我試試

**Comment by vungsung** [comment]
LineageOS刷该kernel会变砖，小弟再另寻他法，感谢!
