### ISSUE TITLE
已解锁却显示 Flashing is not allowed for Critical Partitions.

### ISSUE THREAD

**Issue by d0gkiller87** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#5]
fastboot flashing unlock, fastboot flashing unlock_critical 都用正确流程解锁了，
用flash.bat却出现多次Flashing is not allowed for Critical Partitions.
[v] Wipe all data. 已双清
[v] Unlocked. 已解锁
请问大佬有遇到这个问题吗 非常感谢~!

**Comment by johanlike** [comment]
下载 安卓SDK 工具包 `https://developer.android.com/studio/releases/platform-tools` 将fastboot.exe放在脚本同目录下面。

**Comment by vungsung** [comment]
是的，小弟是用最新的原版platform-tools

**Comment by johanlike** [comment]
你还要解锁引导。

**Comment by johanlike** [comment]
一加是最好解锁的，有不懂的可以用一加论坛的官方工具箱。

**Comment by vungsung** [comment]
問題比較複雜, 先關帖。

**Comment by Z-fly** [comment]
fastboot flashing unlock_critical
