### ISSUE TITLE
flash script 跟直接adb sideload刷ROM有区别吗

### ISSUE THREAD

**Issue by d0gkiller87** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#7]
如题, 谢谢

**Comment by johanlike** [comment]
flash script比adb sideload刷ROM更好。因为这是彻底把手机所有信息删除然后刷入OOS，用adb sideload的方法刷ROM会有文件残留。

**Comment by d0gkiller87** [comment]
感谢回复，一般我用adb sideload前会先wipe所有分区，这样还是没flash乾净吗

**Comment by johanlike** [comment]
我都说了，能用脚本就用脚本。或者你有功夫你可以自己试几次，不要老是问这些低级问题。因为这样再多的开发者也会被你累死，一个个回答普通的问题。我希望你能提一些建设性的建议而不是这些。就比如你第一次提问的问题。懂？

**Comment by d0gkiller87** [comment]
你觉得回答这些问题很烦很低级
我会来找nethunter，也不是完全没底子，完全照着步骤做，换个顺序做，Google各大论坛，重试了一整周没手机能用，绞尽脑汁推理造成错误的原因，别以为我是懒得花力气就伸手要答案的那种人，要是有很多人成功我却没有，那就是我的愚蠢，像上次问的unlock critical partition，问了xda网友说OP6T根本没有unlock critical的功能，而且我第一次问就说已解锁bootloader，你还叫我解锁bootloader，我想说算了。你要是觉得别人都低智商，那就自己开发自己留着用吧，你永远也不会享受到开发给别人用的乐趣，只开发不维护，别人很有礼貌的问了还骂人低级，当初看了你xda的帖子说别人不感谢你还骂你，我还特别同情你，现在我终於知道为什麽了，举报QQ群很没水准，不过你也没好到哪去。

**Comment by johanlike** [comment]
第一我并没有骂你低级，第二你不能用不代表别人不能用，第三我一直在维护。第四没有解锁关键功能的话那为什么要做适配？有本事你拿原生内核去OTG外接那些东西啊。那为什么个个都能用就你要折腾那么久？第五你懂前应后果就知道我的群是因为什么被举报了？别人是拿着我的东西去卖，我怕你们中毒你懂吗？还有，我不是觉得你低智商，而是类似于这种问题问的我实在太多，你试过一天被十几个人问怎么解锁怎么解锁引导，怎么刷入，等等这些问题，问的我都烦了，你说我不回答吧我又怕你觉得是很冷漠，我回答吧，次数又太频繁力不从心。你完全可以不用我的东西，没必要在这里叽叽歪歪的说那么多。

**Comment by d0gkiller87** [comment]
我想为年少无知的自己向您致上最诚挚的歉意  
这种无法自己解决问题、滥用issues发没建设性的问题、还反过来骂无偿付出的开发者，如今的我必定无法像您一般保持风度  
过往几年间我一直感到十分愧疚，但没有勇气面对。希望有机会您能够看到这段话，祝您有个美好的一天。
