### ISSUE TITLE
adb sideload DJY error

### ISSUE THREAD

**Issue by wangmu0579** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#8]
adb sideload DJY-WIFI-firmware-APP-7.0-beta.zip
But phone report me 255. 
See more details on following:

正在开始 ADB sideload…
I:Disabling MTP
Stopping adbd...
linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/recovery" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/recovery" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
I:Setting active slot B
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file'
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /sys/class/backlight/pane10-backlight/brightness
I:Specified brightness file '/sys/class/backlight/pane10-backlight/brightness' not found.
I:Found brightness file at '/sys/devices/platform/soc/ae00000.qcom,mdss_mdp/backlight/panel0-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 420
I:LANG: en
I:AB_OTA_UPDATER := true
I:TW_NO_LEGACY_PROPS := true
sideload-host file size 216983797 block size 65536
正在安装 Zip 刷机包 '/sideload/package.zip'
unknown fuse request opcode 2016
I:Update binary zip
Verifying package compatibility...
Package doesn't contain compatibility.zip entry
I:Zip does not contain SELinux file_contexts file in its root.
E:Can't execute '/tmp/updater': Too many symbolic links encountered
Updater 过程结束，错误：255

I try to use following way upgrade HOS to OOS which avoid clean up all data in my phone:
https://forum.xda-developers.com/showpost.php?p=78026660&postcount=3

TWRP Users
1. Boot into TWRP and Flash the Latest Magisk Uninstaller
2. Flash the latest Full Oxygen OS Zip
3. Flash the TWRP installer Zip
4. Reboot to RECOVERY to make sure TWRP stays and continue to root. 
5. Flash the Latest Magisk to maintain root
6. Reboot System and Enjoy the latest firmware without any data loss

Maybe I should try to flash.sh script install a new OOS. But I really hope I can have a OOS without any data loss.
Thanks in advance.

**Comment by wangmu0579** [comment]
Sorry I use wrong file in previous time, the correct file should be :
adb sideload /home/kali/Downloads/DJY15-3.zip

**Comment by little-dao** [comment]
.... so your issue is solved now ?

**Comment by wangmu0579** [comment]
Yes. My issue solved now.
