### ISSUE TITLE
HID Interfaces

### ISSUE THREAD

**Issue by aerr0R** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#9]
大佬好，安装了您的内核遇到了个问题，Home页提示No HID interfaces detected，这个问题如何解决呢？

**Comment by johanlike** [comment]
新版内核已修复，请按照安装教程更新

**Comment by lisksemen** [comment]
I've installed latest version of the kernel and the issue stayed the same for me

**Comment by johanlike** [comment]
@lisksemen you need to use nethunter APP usbarmy module settings

**Comment by johanlike** [comment]
@lisksemen This is the reference link https://t.me/nethunter666/6146

**Comment by lisksemen** [comment]
Thanks!
